// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALTChjGme4JkJAXqBIo82PJURBF7B3Im0',
    appId: '1:90262009210:web:6f79ba94c5b64c058fd2c3',
    messagingSenderId: '90262009210',
    projectId: 'recipeslab-68f9e',
    authDomain: 'recipeslab-68f9e.firebaseapp.com',
    storageBucket: 'recipeslab-68f9e.firebasestorage.app',
    measurementId: 'G-BXK92PC3VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7pBEeL8oZXCUFKF_MSfixBFy_DVqmiyA',
    appId: '1:90262009210:android:a45cbf7af109d7608fd2c3',
    messagingSenderId: '90262009210',
    projectId: 'recipeslab-68f9e',
    storageBucket: 'recipeslab-68f9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkpI2vdltr0_u2QX_I-SOQn_jrHJOGA3g',
    appId: '1:90262009210:ios:fcf6516db6a9ea388fd2c3',
    messagingSenderId: '90262009210',
    projectId: 'recipeslab-68f9e',
    storageBucket: 'recipeslab-68f9e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApps',
  );
}
